version: '3'
services:
  mall-admin:
    image: mall/mall-admin:1.0-SNAPSHOT
    container_name: mall-admin
    ports:
      - 8092:8092
    volumes:
      - /mydata/app/mall-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
      - 'SERVER_PORT=8092'
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false'
      - 'SPRING_DATASOURCE_USERNAME=root'
      - 'SPRING_DATASOURCE_PASSWORD=123456'
    extra_hosts:
      - "host.docker.internal:host-gateway"
#  mall-search:
#    image: mall/mall-search:1.0-SNAPSHOT
#    container_name: mall-search
#    ports:
#      - 8081:8081
#    volumes:
#      - /mydata/app/mall-search/logs:/var/logs
#      - /etc/localtime:/etc/localtime
#    environment:
#      - 'TZ="Asia/Shanghai"'
#    external_links:
#      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
#      - mysql:db #可以用db这个域名访问mysql服务
  mall-portal:
    image: mall/mall-portal:1.0-SNAPSHOT
    container_name: mall-portal
    ports:
      - 8085:8085
    volumes:
      - /mydata/app/mall-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - mongo:mongo #可以用mongo这个域名访问mongo服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - 'TZ="Asia/Shanghai"'
      - 'SERVER_PORT=8085'
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false'
      - 'SPRING_DATASOURCE_USERNAME=root'
      - 'SPRING_DATASOURCE_PASSWORD=123456'
